# 示例项目元数据

code: EXAMPLE
name: 示例项目

# 跨设备路径 (按优先级排序，AI 自动检测存在的路径)
paths:
  - ~/Projects/example-project

# 任务命名配置
task_naming:
  # 格式选项: full | date | simple | custom
  format: "full"
  # 自定义格式 (仅 format: "custom" 时生效)
  # pattern: "{DATE}-{NNN}_{TAG}{NAME}.md"
  # 序号位数 (默认 3)
  # seq_digits: 3

tech_stack:
  - TypeScript
  - React

created: "2026-01-10"
status: active

tags:
  - demo
  - template

related: []

metadata:
  description: AI-TASK 示例项目，展示基本用法
