# 示例项目元数据

code: EXAMPLE
name: 示例项目

# 跨设备路径 (按优先级排序，AI 自动检测存在的路径)
paths:
  - ~/Projects/example-project

tech_stack:
  - TypeScript
  - React

created: "2026-01-10"
status: active

tags:
  - demo
  - template

related: []

metadata:
  description: AI-TASK 示例项目，展示基本用法
