# AI-TASK 项目元数据模板
# 文件位置: projects/{PROJECT}/project.yaml

# ========== 必需字段 ==========

# 项目代号 (与目录名一致)
code: "{PROJECT_CODE}"

# 项目名称
name: "{PROJECT_NAME}"

# 跨设备路径列表 (按优先级排序，AI 自动检测存在的路径)
paths:
  - ~/path/to/project           # 主力设备
  # - ~/Projects/{PROJECT}      # 备用路径
  # - /home/user/projects/{PROJECT}  # Linux 路径

# ========== 可选字段 ==========

# 任务命名配置
task_naming:
  # 文件名格式 (可选值见下方说明)
  # - "full"    : {YYYYMMDD}-{NNN}_[标签]任务名称.md  (推荐，完整格式)
  # - "date"    : {YYYYMMDD}-{NNN}_任务名称.md        (日期+序号，无标签)
  # - "simple"  : {NNN}-任务名称.md                   (仅序号，最简)
  # - "custom"  : 使用下方 pattern 自定义
  format: "full"
  
  # 自定义格式 (仅当 format: "custom" 时生效)
  # 可用变量: {DATE}, {NNN}, {TAG}, {NAME}
  # pattern: "{DATE}-{NNN}_{TAG}{NAME}.md"
  
  # 序号位数 (默认 3，即 001-999)
  # seq_digits: 3

# 技术栈
tech_stack:
  - Tech1
  - Tech2

# 创建时间
created: "YYYY-MM-DD"

# 项目状态: active | paused | archived
status: active

# 标签
tags: []

# 关联项目
related: []

# 扩展元数据
metadata:
  # author: ""
  # version: ""
